"""
Report Generator - Create professional reports in multiple formats
Supports: HTML, Excel, Word, Markdown
"""
import io
import base64
from datetime import datetime
from typing import Dict, List, Any, Optional
import pandas as pd
import numpy as np
import streamlit as st

class ReportGenerator:
    """Generate comprehensive data reports in multiple formats."""

    @staticmethod
    def generate_html_report(df: pd.DataFrame, title: str = "Data Report",
                              sections: Dict[str, Any] = None) -> str:
        """Generate a beautiful HTML report."""

        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>{title}</title>
            <style>
                @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
                * {{ margin: 0; padding: 0; box-sizing: border-box; }}
                body {{
                    font-family: 'Inter', sans-serif;
                    background: #0E1117;
                    color: #FAFAFA;
                    line-height: 1.6;
                    padding: 40px;
                }}
                .container {{ max-width: 1200px; margin: 0 auto; }}
                .header {{
                    background: linear-gradient(135deg, #00D4AA 0%, #6C63FF 100%);
                    padding: 40px;
                    border-radius: 16px;
                    margin-bottom: 30px;
                    color: #0E1117;
                }}
                .header h1 {{ font-size: 2.5rem; font-weight: 700; margin-bottom: 10px; }}
                .header p {{ font-size: 1rem; opacity: 0.8; }}
                .section {{
                    background: #1C1F26;
                    border: 1px solid #2A2D35;
                    border-radius: 12px;
                    padding: 30px;
                    margin-bottom: 20px;
                }}
                .section h2 {{
                    color: #00D4AA;
                    font-size: 1.5rem;
                    margin-bottom: 20px;
                    padding-bottom: 10px;
                    border-bottom: 2px solid #00D4AA;
                }}
                table {{
                    width: 100%;
                    border-collapse: collapse;
                    margin: 20px 0;
                    font-size: 0.9rem;
                }}
                th {{
                    background: #00D4AA;
                    color: #0E1117;
                    padding: 12px;
                    text-align: left;
                    font-weight: 600;
                }}
                td {{
                    padding: 10px 12px;
                    border-bottom: 1px solid #2A2D35;
                }}
                tr:hover {{ background: #252A33; }}
                .metric-grid {{
                    display: grid;
                    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                    gap: 15px;
                    margin: 20px 0;
                }}
                .metric-card {{
                    background: #252A33;
                    border: 1px solid #2A2D35;
                    border-radius: 10px;
                    padding: 20px;
                    text-align: center;
                }}
                .metric-value {{
                    font-size: 2rem;
                    font-weight: 700;
                    color: #00D4AA;
                }}
                .metric-label {{
                    font-size: 0.85rem;
                    color: #888;
                    margin-top: 5px;
                    text-transform: uppercase;
                    letter-spacing: 0.05em;
                }}
                .footer {{
                    text-align: center;
                    padding: 20px;
                    color: #666;
                    font-size: 0.85rem;
                    margin-top: 40px;
                }}
                .badge {{
                    display: inline-block;
                    padding: 4px 12px;
                    border-radius: 20px;
                    font-size: 0.75rem;
                    font-weight: 600;
                    margin: 2px;
                }}
                .badge-success {{ background: #00D4AA22; color: #00D4AA; border: 1px solid #00D4AA44; }}
                .badge-warning {{ background: #F39C1222; color: #F39C12; border: 1px solid #F39C1244; }}
                .badge-error {{ background: #E74C3C22; color: #E74C3C; border: 1px solid #E74C3C44; }}
                .timestamp {{ color: #666; font-size: 0.85rem; margin-top: 5px; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>{title}</h1>
                    <p>Generated by data_all1 Intelligence Platform</p>
                    <p class="timestamp">{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
                </div>
        """

        # Overview Section
        html += """
                <div class="section">
                    <h2>Dataset Overview</h2>
                    <div class="metric-grid">
        """
        html += f"""
                        <div class="metric-card">
                            <div class="metric-value">{df.shape[0]:,}</div>
                            <div class="metric-label">Rows</div>
                        </div>
                        <div class="metric-card">
                            <div class="metric-value">{df.shape[1]}</div>
                            <div class="metric-label">Columns</div>
                        </div>
                        <div class="metric-card">
                            <div class="metric-value">{df.isnull().sum().sum():,}</div>
                            <div class="metric-label">Missing Values</div>
                        </div>
                        <div class="metric-card">
                            <div class="metric-value">{df.duplicated().sum():,}</div>
                            <div class="metric-label">Duplicate Rows</div>
                        </div>
                    </div>
                </div>
        """

        # Data Types Section
        html += """
                <div class="section">
                    <h2>Column Summary</h2>
                    <table>
                        <tr>
                            <th>Column</th>
                            <th>Type</th>
                            <th>Non-Null</th>
                            <th>Unique</th>
                            <th>Missing %</th>
                        </tr>
        """
        for col in df.columns:
            missing_pct = df[col].isnull().mean() * 100
            badge_class = "badge-error" if missing_pct > 20 else "badge-warning" if missing_pct > 5 else "badge-success"
            html += f"""
                        <tr>
                            <td><strong>{col}</strong></td>
                            <td>{str(df[col].dtype)}</td>
                            <td>{df[col].notna().sum():,}</td>
                            <td>{df[col].nunique():,}</td>
                            <td><span class="badge {badge_class}">{missing_pct:.1f}%</span></td>
                        </tr>
            """
        html += "</table></div>"

        # Numeric Summary
        numeric_df = df.select_dtypes(include=[np.number])
        if not numeric_df.empty:
            html += """
                <div class="section">
                    <h2>Numeric Summary</h2>
                    <table>
                        <tr>
                            <th>Column</th>
                            <th>Mean</th>
                            <th>Median</th>
                            <th>Std</th>
                            <th>Min</th>
                            <th>Max</th>
                            <th>Skewness</th>
                        </tr>
            """
            for col in numeric_df.columns:
                html += f"""
                        <tr>
                            <td><strong>{col}</strong></td>
                            <td>{numeric_df[col].mean():.4f}</td>
                            <td>{numeric_df[col].median():.4f}</td>
                            <td>{numeric_df[col].std():.4f}</td>
                            <td>{numeric_df[col].min():.4f}</td>
                            <td>{numeric_df[col].max():.4f}</td>
                            <td>{numeric_df[col].skew():.4f}</td>
                        </tr>
                """
            html += "</table></div>"

        # Custom Sections
        if sections:
            for section_title, content in sections.items():
                html += f"""
                <div class="section">
                    <h2>{section_title}</h2>
                    <pre style="background:#0E1117;padding:15px;border-radius:8px;overflow-x:auto;">{content}</pre>
                </div>
                """

        html += """
                <div class="footer">
                    <p>Generated with data_all1 | Data Intelligence Platform</p>
                </div>
            </div>
        </body>
        </html>
        """

        return html

    @staticmethod
    def generate_excel_report(df: pd.DataFrame, sheets: Dict[str, pd.DataFrame] = None) -> bytes:
        """Generate Excel workbook with multiple sheets."""
        output = io.BytesIO()

        with pd.ExcelWriter(output, engine='xlsxwriter') as writer:
            workbook = writer.book

            # Define formats
            header_format = workbook.add_format({
                'bold': True,
                'bg_color': '#00D4AA',
                'font_color': '#0E1117',
                'border': 1,
                'font_size': 11
            })

            title_format = workbook.add_format({
                'bold': True,
                'font_size': 16,
                'font_color': '#00D4AA'
            })

            cell_format = workbook.add_format({
                'border': 1,
                'border_color': '#2A2D35'
            })

            # Main data sheet
            df.to_excel(writer, sheet_name='Data', index=False)
            worksheet = writer.sheets['Data']

            for col_num, value in enumerate(df.columns.values):
                worksheet.write(0, col_num, value, header_format)
                max_len = max(df[value].astype(str).map(len).max(), len(str(value))) + 2
                worksheet.set_column(col_num, col_num, min(max_len, 50))

            # Summary sheet
            summary_data = {
                'Metric': ['Rows', 'Columns', 'Missing Values', 'Duplicate Rows', 'Memory (MB)'],
                'Value': [
                    df.shape[0],
                    df.shape[1],
                    df.isnull().sum().sum(),
                    df.duplicated().sum(),
                    round(df.memory_usage(deep=True).sum() / 1024 / 1024, 2)
                ]
            }
            summary_df = pd.DataFrame(summary_data)
            summary_df.to_excel(writer, sheet_name='Summary', index=False)
            summary_ws = writer.sheets['Summary']
            for col_num, value in enumerate(summary_df.columns.values):
                summary_ws.write(0, col_num, value, header_format)
            summary_ws.set_column(0, 0, 20)
            summary_ws.set_column(1, 1, 15)

            # Additional sheets
            if sheets:
                for sheet_name, sheet_df in sheets.items():
                    sheet_df.to_excel(writer, sheet_name=sheet_name[:31], index=False)
                    ws = writer.sheets[sheet_name[:31]]
                    for col_num, value in enumerate(sheet_df.columns.values):
                        ws.write(0, col_num, value, header_format)

        return output.getvalue()

    @staticmethod
    def generate_markdown_report(df: pd.DataFrame, title: str = "Data Report") -> str:
        """Generate Markdown report."""
        md = f"# {title}\n\n"
        md += f"*Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n\n"
        md += "---\n\n"

        md += "## Overview\n\n"
        md += f"- **Rows**: {df.shape[0]:,}\n"
        md += f"- **Columns**: {df.shape[1]}\n"
        md += f"- **Missing Values**: {df.isnull().sum().sum():,}\n"
        md += f"- **Duplicate Rows**: {df.duplicated().sum():,}\n\n"

        md += "## Columns\n\n"
        md += "| Column | Type | Non-Null | Unique | Missing % |\n"
        md += "|--------|------|----------|--------|-----------|\n"
        for col in df.columns:
            md += f"| {col} | {df[col].dtype} | {df[col].notna().sum():,} | {df[col].nunique():,} | {df[col].isnull().mean()*100:.1f}% |\n"

        md += "\n## Numeric Summary\n\n"
        numeric_df = df.select_dtypes(include=[np.number])
        if not numeric_df.empty:
            md += numeric_df.describe().to_markdown()

        return md
