"""
Report Generator - Export reports in multiple formats
Refactored: No Streamlit dependencies
"""
from typing import Dict, Any, Optional
import io
import pandas as pd
import numpy as np
from datetime import datetime


class ReportGenerator:
    """Generate reports in HTML, Excel, Markdown formats."""

    @staticmethod
    def generate_html_report(df: pd.DataFrame, title: str = "Data Analysis Report",
                            include_eda: bool = True, include_visualizations: bool = True,
                            include_modeling: bool = False) -> str:
        """Generate comprehensive HTML report."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; background: #f5f5f5; color: #333; }}
        .container {{ max-width: 1200px; margin: 0 auto; background: white; padding: 40px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        h1 {{ color: #00D4AA; border-bottom: 3px solid #00D4AA; padding-bottom: 10px; }}
        h2 {{ color: #2C3E50; margin-top: 30px; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ padding: 12px; text-align: left; border: 1px solid #ddd; }}
        th {{ background-color: #00D4AA; color: white; }}
        tr:nth-child(even) {{ background-color: #f9f9f9; }}
        .stat-card {{ background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 10px 0; }}
        .highlight {{ color: #00D4AA; font-weight: bold; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{title}</h1>
        <p>Generated: <span class="highlight">{timestamp}</span></p>

        <h2>Dataset Overview</h2>
        <div class="stat-card">
            <p><strong>Rows:</strong> {df.shape[0]:,}</p>
            <p><strong>Columns:</strong> {df.shape[1]}</p>
            <p><strong>Memory Usage:</strong> {df.memory_usage(deep=True).sum() / 1024:.2f} KB</p>
        </div>

        <h2>Data Types Summary</h2>
        <table>
            <tr><th>Column</th><th>Type</th><th>Non-Null Count</th><th>Missing %</th></tr>
"""
        for col in df.columns:
            dtype = str(df[col].dtype)
            non_null = df[col].notna().sum()
            missing_pct = df[col].isnull().mean() * 100
            html += f"            <tr><td>{col}</td><td>{dtype}</td><td>{non_null:,}</td><td>{missing_pct:.1f}%</td></tr>\n"

        html += """        </table>

        <h2>Numeric Statistics</h2>
"""
        numeric_df = df.select_dtypes(include=[np.number])
        if not numeric_df.empty:
            desc = numeric_df.describe().round(2)
            html += desc.to_html(classes='stats-table')

        if include_eda:
            html += """
        <h2>Data Quality Issues</h2>
        <div class="stat-card">
"""
            missing_cols = df.columns[df.isnull().any()].tolist()
            if missing_cols:
                html += "<p><strong>Columns with missing values:</strong></p><ul>"
                for col in missing_cols:
                    pct = df[col].isnull().mean() * 100
                    html += f"<li>{col}: {pct:.1f}% missing</li>"
                html += "</ul>"
            else:
                html += "<p>No missing values detected. ✅</p>"

            dup_count = df.duplicated().sum()
            html += f"<p><strong>Duplicate rows:</strong> {dup_count:,}</p>"
            html += "</div>"

        html += f"""
        <div class="footer">
            <p>Report generated by FINESE2 Data Intelligence Platform</p>
        </div>
    </div>
</body>
</html>"""
        return html

    @staticmethod
    def generate_excel_report(df: pd.DataFrame, title: str = "Data Analysis Report") -> bytes:
        """Generate Excel report."""
        buffer = io.BytesIO()
        with pd.ExcelWriter(buffer, engine='xlsxwriter') as writer:
            # Summary sheet
            summary_data = {
                'Metric': ['Total Rows', 'Total Columns', 'Memory Usage (KB)', 'Duplicate Rows'],
                'Value': [
                    df.shape[0], df.shape[1],
                    df.memory_usage(deep=True).sum() / 1024,
                    df.duplicated().sum()
                ]
            }
            pd.DataFrame(summary_data).to_excel(writer, sheet_name='Summary', index=False)

            # Data sheet
            df.to_excel(writer, sheet_name='Data', index=False)

            # Statistics sheet
            numeric_df = df.select_dtypes(include=[np.number])
            if not numeric_df.empty:
                desc = numeric_df.describe().round(2)
                desc.to_excel(writer, sheet_name='Statistics')

            # Missing values sheet
            missing = df.isnull().sum()
            missing_pct = (df.isnull().sum() / len(df) * 100).round(2)
            missing_df = pd.DataFrame({'Missing_Count': missing, 'Missing_Pct': missing_pct})
            missing_df = missing_df[missing_df['Missing_Count'] > 0].sort_values('Missing_Count', ascending=False)
            if not missing_df.empty:
                missing_df.to_excel(writer, sheet_name='Missing Values')

            # Format workbook
            workbook = writer.book
            header_format = workbook.add_format({
                'bold': True, 'bg_color': '#00D4AA', 'font_color': 'white', 'border': 1
            })

            for worksheet in writer.sheets.values():
                worksheet.set_column('A:Z', 15)
                for col_num, value in enumerate(worksheet.table[0] if hasattr(worksheet, 'table') else []):
                    worksheet.write(0, col_num, value, header_format)

        buffer.seek(0)
        return buffer.getvalue()

    @staticmethod
    def generate_markdown_report(df: pd.DataFrame, title: str = "Data Analysis Report") -> str:
        """Generate Markdown report."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        md = f"""# {title}

**Generated:** {timestamp}

---

## Dataset Overview

| Metric | Value |
|--------|-------|
| Total Rows | {df.shape[0]:,} |
| Total Columns | {df.shape[1]} |
| Memory Usage | {df.memory_usage(deep=True).sum() / 1024:.2f} KB |
| Duplicate Rows | {df.duplicated().sum():,} |

## Column Information

| Column | Type | Non-Null | Missing % |
|--------|------|----------|-----------|
"""
        for col in df.columns:
            dtype = str(df[col].dtype)
            non_null = df[col].notna().sum()
            missing_pct = df[col].isnull().mean() * 100
            md += f"| {col} | {dtype} | {non_null:,} | {missing_pct:.1f}% |\n"

        numeric_df = df.select_dtypes(include=[np.number])
        if not numeric_df.empty:
            md += "\n## Numeric Statistics\n\n"
            desc = numeric_df.describe().round(2)
            md += desc.to_markdown()

        md += "\n---\n*Report generated by FINESE2 Data Intelligence Platform*\n"
        return md
